name: Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Setup golang 1.19
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Add hosts
        run: cat ${GITHUB_WORKSPACE}/hosts | sudo tee -a /etc/hosts
      - name: Test
        run: go test

